### ISSUE TITLE
main.py error

### ISSUE THREAD

**Issue by hfleitas** [anshulsharmas/F1_ADX#2]
```
3 Event ID:  <class 'ctypes.c_ubyte'>
['__class__', '__class_getitem__', '__ctypes_from_outparam__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_b_base_', '_b_needsfree_', '_length_', '_objects', '_type_']
3 Event ID:  <class 'ctypes.c_ubyte'>
Traceback (most recent call last):
  File "C:\hiram-msft\F1_ADX\main.py", line 234, in <module>
    ingest_participantdata(packet,m_header)
  File "C:\hiram-msft\F1_ADX\main.py", line 118, in ingest_participantdata
    participantdata.m_name.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by hfleitas** [comment]
set game telemetry setting UDP format to 2019 fixed it.
